default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  host: localhost
  port: 5432
  database: hf_development
  username: admin
  password: example

test:
  <<: *default
  host: localhost
  port: 5432
  database: hf_test
  username: admin
  password: example

production:
  <<: *default
  database: db/production.sqlite3
